# Site settings
title: Ihor Kovalyshyn
description: 'Data Science Engineer'
url: 'delta1epsilon.github.io'
baseurl: '/'
google_analytics: 'UA-91445583-1'
disqus_shortname: 'delta1epsilon-github-io'

author:
  name: 'Ihor Kovalyshyn'
  email: ihorko.kovalyshyn@gmail.com
  twitter_username:
  facebook_username:
  github_username:  delta1epsilon
  linkedin_username: ihor-kovalyshyn-a61a7ab8

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
